### ISSUE TITLE
可以转成小程序吗

### ISSUE THREAD

**Issue by dahgn** [erich2s/maintenance-management-system#10]

**Comment by erich2s** [comment]
转不了，都不是一个东西，虽然你可以在小程序放webview？

**Comment by dahgn** [comment]
> 转不了，都不是一个东西，虽然你可以在小程序放webview？

还真行，舒服了，就是不知道代价是什么

**Comment by dahgn** [comment]
后端能移植到nest吗

**Comment by erich2s** [comment]
> 后端能移植到nest吗

移不了

**Comment by dahgn** [comment]
> Owner
管理端用户管理页面，点击下一页的时候页面卡死，带page和size参数的分页的fetch请求一直待定，后端接口测过了没问题

**Comment by dahgn** [comment]
> > Owner
> > 管理端用户管理页面，点击下一页的时候页面卡死，带page和size参数的分页的fetch请求一直待定，后端接口测过了没问题
好了，把这段注释了就正常了，太诡异了
  useEffect(() => {
    // 获取tableRef的高度
    const tbh = tableRef.current?.clientHeight;
    // 从而动态设置page size
    setSize(Math.floor(tbh! / 55));
  }, [tableRef.current?.clientHeight]);

**Comment by erich2s** [comment]
大学时候写的了，那时候写的地方有好多的不规范哈哈哈
